name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known_hosts
      run: ssh-keyscan -H 83.220.174.239 >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh -T deployuser@83.220.174.239 <<EOF
          cd articles-analyzer
          git reset --hard HEAD
          git pull origin main
          docker-compose down
          docker-compose up --build -d
        EOF